---

- name: add Confluent repository key
  apt_key:
    url: https://packages.confluent.io/deb/{{ confluent_version }}/archive.key
    state: present

- name: add Confluent repository
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  with_items:
    - deb [arch=amd64] https://packages.confluent.io/deb/{{ confluent_version }} stable main

- name: install Java
  become: true
  apt:
    name: openjdk-11-jdk
    state: latest
    update_cache: yes

- name: install Confluent platform
  apt:
    name: confluent-platform

- name: set owner/group of ZK data directory
  file:
    path: "{{ zk_datadir }}"
    owner: cp-kafka
    group: root
    state: directory

- name: create myid file
  template:
    src: templates/myid.j2
    dest: "{{ zk_datadir }}/myid"
    owner: cp-kafka
    group: root
    mode: 0644
    backup: true
  notify: restart zookeeper

- name: set zookeeper.properties file
  template:
    src: templates/zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.properties
    owner: cp-kafka
    group: root
    mode: 0644
    backup: true
  notify: restart zookeeper

- name: add zookeeper.service systemd file
  become: true
  template:
    src: templates/zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify: restart systemd and restart zookeeper

- name: start zookeeper
  systemd:
    name: zookeeper
    enabled: true
    state: started
