---
- name: Setup EBS Volume
  hosts: ecommerce, prometheus
  connection: ssh
  become: true      
  gather_facts: yes

  vars:
    block_name: /dev/nvme1n1
    mount_point: /mnt/storage
    filesystem_type: xfs

  tasks:
    - name: Format single NVMe disk
      filesystem:
        fstype: "{{ filesystem_type }}"
        dev: "{{ block_name }}"

    - name: Create mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Mount NVMe disk to the mount point
      mount:
        path: "{{ mount_point }}"
        src: "{{ block_name }}"
        fstype: "{{ filesystem_type }}"
        opts: defaults,noatime,nodiscard
        state: mounted
