version: '3'
services:
  pinot-zookeeper:
    image: zookeeper:3.8.4
    container_name: pinot-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pinot-demo

  pinot-controller:
    image: apachepinot/pinot:1.3.0
    command: "StartController -zkAddress pinot-zookeeper:2181"
    container_name: pinot-controller
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "7070:7070"
    environment:
      JAVA_OPTS: "-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar=7070:/opt/prometheus/pinot.yaml -Dplugins.dir=/opt/pinot/plugins -Xms512M -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
    volumes:
      # Mount the JMX exporter JAR from host to container
      - /opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar:/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar:ro
      # Mount the JMX exporter config from host to container
      - /opt/prometheus/pinot.yaml:/opt/prometheus/pinot.yaml:ro
    depends_on:
      - pinot-zookeeper
    networks:
      - pinot-demo

  pinot-broker:
    image: apachepinot/pinot:1.3.0
    command: "StartBroker -zkAddress pinot-zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-broker"
    ports:
      - "8099:8099"
      - "7080:7080"
    environment:
      JAVA_OPTS: "-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar=7080:/opt/prometheus/pinot.yaml -Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-broker.log"
    volumes:
      # Mount the JMX exporter JAR from host to container
      - /opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar:/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar:ro
      # Mount the JMX exporter config from host to container
      - /opt/prometheus/pinot.yaml:/opt/prometheus/pinot.yaml:ro
    depends_on:
      pinot-zookeeper:
        condition: service_started
      pinot-controller:
        condition: service_started
    networks:
      - pinot-demo

  pinot-server:
    image: apachepinot/pinot:1.3.0
    command: "StartServer -zkAddress pinot-zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-server"
    ports:
      - "8098:8098"
      - "7090:7090"
    environment:
      JAVA_OPTS: "-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar=7090:/opt/prometheus/pinot.yaml -Dplugins.dir=/opt/pinot/plugins -Xms2G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log"
    volumes:
      # Mount the JMX exporter JAR from host to container
      - /opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar:/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar:ro
      # Mount the JMX exporter config from host to container
      - /opt/prometheus/pinot.yaml:/opt/prometheus/pinot.yaml:ro
    depends_on:
      pinot-zookeeper:
        condition: service_started
      pinot-broker:
        condition: service_started
      pinot-controller:
        condition: service_started
    networks:
      - pinot-demo

networks:
  pinot-demo:
    name: pinot-demo
